[tools]
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.27.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.18.1" }
rotrieve = { source = "roblox/rotriever", version = "=0.5.13-alpha.5" }
lest = { source = "Roblox/lest", version = "3.8.0" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "=5.8.0" }
